### ISSUE TITLE
Feature request: search conversion

### ISSUE THREAD

**Issue by kastiglione** [liblit/demangle-mode#3]
It would be nice to search a buffer for a symbol by its demangled name.

**Comment by liblit** [comment]
I agree that this would be nice. I just don’t know a good way to make it happen, which is why this is documented as a [known issue](https://github.com/liblit/demangle-mode#known-issues-and-design-limitations). The standard non-interactive search functions like `search-forward` and `re-search-forward` are implemented in C and apparently have no provision for searching within the `display` text property we use to show demangled names. Interactive search commands like `isearch-forward` and `isearch-forward-regexp` then build on the non-interactive search functions, so they have the same limitation.

I don’t see any way to pull this off short of replacing `re-search-forward` and kin with my own implementations, presumably created from scratch in Emacs Lisp. That does not sound like a wise approach. @kastiglione, do you have any better ideas for how to do this? Do you know of any other Emacs packages that do something similar, that I could use as exemplars?

**Comment by kastiglione** [comment]
I missed the known issues, thank you for the pointer and the context here. I agree re-implementing doesn't sound wise. I don't have any better ideas, and don't know of other packages to learn from. I'll keep these questions in mind in case I come across something, or get an idea.

**Comment by liblit** [comment]
OK, I am going to close this and tag it `wontfix` for now. If you come up with a workable strategy, feel free to add a comment here and I will reopen the bug. Sorry I can’t do more for you now!
