### ISSUE TITLE
Generalize to demangle other languages

### ISSUE THREAD

**Issue by nordlow** [liblit/demangle-mode#7]
It would be great if this mode was generalized to cover demangling of other languages, in my case, Dlang.

Such a generalization would mainly consist of stripping the sub-string `c++-filt` from symbols

-  `demangle-c++filt-executable`, and
- `demangle-c++filt-args`, and
- demangle--c++filt-command, 

and making these mode-local and maybe also buffer-local.

In D's case this executable is named `"ddemangle"` ([source](https://github.com/dlang/tools/blob/master/ddemangle.d)) instead of `"c++filt"`.

**Comment by liblit** [comment]
Adding D support sounds like a grand idea. Thanks for suggesting this, @nordlow.

Presumably we would also need to customize `demangle-font-lock-keywords`. My understanding is that mangled D names begin with `_D` rather than `_Z` as used for mangled C++ under the Itanium ABI scheme. So it seems we would need some sort of association list mapping each supported major mode to the corresponding demangler executable, demangler argument list, and the regular expression part of the font-lock keywords.

Realistically, I will get around to this *eventually* but perhaps not promptly. I'd welcome a pull request from you if you want to give it a try.

**Comment by nordlow** [comment]
BTW: it would be a good idea to propose

(add-hook 'compilation-mode-hook 'demangle-mode)

in the intro docs. As linker errors are typically where a developer often encounters mangled symbols.

**Comment by nordlow** [comment]
LGTM. I have only one comment on the implementation; will `demangle-mode` work efficiently in buffers that are fed output from an external process such as in `compilation-mode`? That only demangles the parts (lines) that are added at the end?

**Comment by liblit** [comment]
> will `demangle-mode` work efficiently in buffers that are feed output from an external process such as in `compilation-mode`? That is only demangle the parts (lines) that are added at the end?

Yes, thanks to years of optimization work on `font-lock-mode`, which is what `demangle-mode` uses under the hood.

**Comment by liblit** [comment]
> BTW: it would be a good idea to propose using
> 
> ```elisp
> (add-hook 'compilation-minor-mode-hook 'demangle-mode)
> ```

Thanks, that's a nice idea. Added in 541ba39cb8954285da5c1d05a059546bbe415108.

**Comment by liblit** [comment]
For the record, `demangle-mode` [now supports Rust](https://github.com/liblit/demangle-mode/commit/04f545adab066708d6151f13da65aaf519f8ac4e) too.
